# Generated by Django 3.0.7 on 2020-07-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_book_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='page_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('to read', 'to read'), ('reading', 'reading'), ('read', 'read')], default=1, max_length=10),
        ),
    ]
