# Generated by Django 3.0.7 on 2020-07-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200727_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
